kind: pipeline
type: docker
name: default

trigger:
  branch:
  - master

steps:
  - name: Build EspoCRM Docker image
    image: plugins/docker
    settings:
      repo: registry.mrfriendly.uk/espocrm
      tags:
      - latest
      registry: registry.mrfriendly.uk

  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: discord_webhook
      username: Drone CI/CD - EspoCRM Docker Image 
    when:
      status: [ failure ]
