kind: pipeline
type: docker
name: espocrm-docker

trigger:
  event:
  - tag

steps:
  - name: Build EspoCRM Docker image
    image: plugins/docker
    settings:
      repo: docker-registry.k8s.array21.dev/espocrm
      tags:
      - latest
      - ${DRONE_TAG}
      registry: docker-registry.k8s.array21.dev

  - name: Deploy to Kubernetes
    image: ubuntu:latest
    environment:
      DEBIAN_FRONTEND: noninteractive
      SSH_KEY:
        from_secret: ssh_key
    commands:
    - apt update && apt install -y openssh-client
    
    - mkdir -p $HOME/.ssh/
    - eval `ssh-agent`
    - echo "$SSH_KEY" | tr -d '\r' | ssh-add - > /dev/null

    - rm -rf $HOME/.ssh/config
    - touch $HOME/.ssh/config
    - echo "Host *\n\tStrictHostKeyChecking no" > $HOME/.ssh/config
    
    - "ssh droneci@kube-ssh.intern.array21.dev kubectl set image -n mrfriendly deployment/espocrm espocrm=docker-registry.k8s.array21.dev/espocrm:${DRONE_TAG}"
      
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: discord_webhook
      username: Drone CI/CD - EspoCRM Docker Image 
    when:
      status: [ failure ]
